### ISSUE TITLE
Does the fork of the singularity project cause issues for this lesson?

### ISSUE THREAD

**Issue by aturner-epcc** [carpentries-incubator/singularity-introduction#8]
The singularity community is in a bit of turmoil at the moment. The singularity docker container (> v3.7.4) is currently based on the sylabs version, see:

https://github.com/singularityhub/singularity-docker

but older ones (and this lesson specifies 3.5.3) were based on the hpcng version.

I think we need to be specific about which version of singularity we are assuming for this lesson and suspect the sylabs version is the right choice for now as this is what the docker versions (and, I guess the distro repo versions) are based on.

**Comment by jcohen02** [comment]
I think this is probably covered in the discussion in #9? Closing this for now but feel free to reopen @aturner-epcc if you think it would be useful to have a separate discussion here with regard to this issue.
